### ISSUE TITLE
QUESTION:  change them colors of flow screens

### ISSUE THREAD

**Issue by alexlovar** [GetMati/mati-flutter-plugin#1]
Hi, thank you so much for this plugin!!, i have a question, by default the theme color of the flow screens is blue, i like to integrate this with my app, but i need to change to a personalized color, it is possible? if yes how i do this?

**Comment by aposnovmati** [comment]
Hello @alexlovar do you want to change the color of the button or the background of the screens when the button clicked and flow started?

**Comment by alexlovar** [comment]
Not, i'm refered to the flow inside screens, i can see the language selector and my company logo in the app bar, at the botom the color button is blue, for example the "Start" or "Allow access", "Next", "Take a photo", etc. is possible to personalized this theme colors with the plugin?

**Comment by aposnovmati** [comment]
@alexlovar we plan to add it next version
