### ISSUE TITLE
Cancelling the flow gets stuck in cancelled state

### ISSUE THREAD

**Issue by chjdev** [GetMati/mati-flutter-plugin#2]
We are listening for SDK events as described:

```dart
    matiSubscription = MatiFlutter.resultCompleter.future.asStream().listen((event) {
      log('KYC $event');
    });
```
Our code works for completing the flow successfully, however if we cancel the flow (via `X` -> cancel) all subsequent events will be cancelled events.

We tried different approaches with restarting the flow however it seems to be reliant on an internal state that doesn't get reset.

Tested on iOS 14.6 with
```
  - Mati-Global-ID-SDK (3.2.3)
  - mati_plugin_flutter (2.0.0):
    - Flutter
    - Mati-Global-ID-SDK
 ```

**Comment by aposnovmati** [comment]
Hello @chjdev sorry for the long wait for the answer, we will investigate it and return to you next week.

**Comment by chjdev** [comment]
@aposnovmati it's been a while now, any updates on this?

**Comment by aposnovmati** [comment]
Hello @chjdev Is it possible to somehow configure/change the logic of your app with the plugin so that it works? coz i think we can take this issue to research only at end of this month

**Comment by chjdev** [comment]
thank you for your response, we're pretty sure having `resultCompleter` as a global static final is to blame for the behavior.

only investigating this at the end of the month is frankly disappointing.

**Comment by aposnovmati** [comment]
Hello @chjdev we have just take your issue to investigation and will return to you later this week

**Comment by aposnovmati** [comment]
Hello @chjdev could you try, please new 2.3.1 version, we will wait for your feedback

**Comment by dev-whjc** [comment]
It worked, thank you!

Unfortunately, the `resultCompleter` is now `untyped/dynamic` but we can cast it to `Future<Result>`.
