### ISSUE TITLE
Fatal exception when sentry_flutter is a project dependency

### ISSUE THREAD

**Issue by victormarques-ia** [GetMati/mati-flutter-plugin#4]
The exception occurs when calling **MatiFlutter.showMatiFlow()**, just because the **sentry** is in the project. I tried different versions of **mati_plugin_flutter** and **sentry_flutter**, but the exception is the same
![a](https://user-images.githubusercontent.com/60486864/128099597-556e190d-33e2-44ac-b3e0-86303dc503e2.jpg)

**Dependency versions:**

```
  mati_plugin_flutter: ^2.2.0                                           
  sentry_flutter: ^5.1.0
```

**Comment by aposnovmati** [comment]
Hello @victormarques-ia we will investigate it, and return to you next week

**Comment by hpadrao** [comment]
Any news?

**Comment by aposnovmati** [comment]
Hello @hpadrao @victormarques-ia we have just released 2.3.0 version plugin with fix this issue, please try it

**Comment by victormarques-ia** [comment]
Hello @aposnovmati, the error with sentry sdk was really fixed, but there is another problem occurring when I try to run any environment in release or even run an apk, it crashes again when I call **MatiFlutter.showMatiFlow()**.
The error doesn't happen when I run in debug.

**I also made sure the android minSdkVersion is at 21.**

**commands:**

- flutter run --flavor dev -t lib/main_dev.dart --release
- flutter run --flavor dev -t lib/main_dev.dart

![fix](https://user-images.githubusercontent.com/60486864/129348858-ca927c46-4fc6-45ec-bd00-2de4c0bda6c8.png)

**Comment by aposnovmati** [comment]
Hello @victormarques-ia we will investigate it and return to you early next week

**Comment by victormarques-ia** [comment]
> Hello @victormarques-ia we will investigate it and return to you early next week

Ok, it would also be interesting to observe the behavior in IOS, in an initial test it gave an error when running in debug,
between sentry and mati, using version **2.3.0** that came out today with fixes for Android.

**Comment by aposnovmati** [comment]
@victormarques-ia hello, let's have a call, to investigate it in real-time in an online meeting?

**Comment by aposnovmati** [comment]
sorry @victormarques-ia what company company do you present?

**Comment by victormarques-ia** [comment]
> sorry @victormarques-ia what company company do you present?

Hi, I heard that someone from Mati's team is going to have a call with the technical leader of our project, so I think this is underway.

Regarding android, it was only possible to solve the build problem when I updated the

```
 dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
 }
 ```
for version **4.1.0+**, i ended up leaving it in version **7.0.0 with grandle in 7.0.2**. So far this has definitely solved the problem.

In IOS we identified that there was this change in the **MatiSDK call to only Mati**, but the import is **still MatiSDK**, so this is generating an error at build time.

![b](https://user-images.githubusercontent.com/60486864/129786971-5eeead17-cee8-4639-bf84-a851c56894b4.png)
![g](https://user-images.githubusercontent.com/60486864/129787104-26127b2f-0352-465b-b85c-59c8203667da.png)

**Comment by aposnovmati** [comment]
Hello @victormarques-ia so it works for iOS or no?) do you have issues? (yes we changed MatiSDK.shared.showMatiFLow to Mati.shared.showMatiFlow in latest version of iOS SDK)

**Comment by victormarques-ia** [comment]
> Hello @victormarques-ia so it works for iOS or no?) do you have issues? (yes we changed MatiSDK.shared.showMatiFLow to Mati.shared.showMatiFlow in latest version of iOS SDK)

So apparently the problem in IOS was the local .pubcache that was holding an old version of the native MatiSDK, even when flutter installed the most up-to-date version. After a few hours we managed to solve it by forcibly removing these files.
Thank you very much for the attention in the last few days, let's do some more tests but I believe that the problems in both IOS and Android are solved.

**Comment by aposnovmati** [comment]
Hello @victormarques-ia ok, thanks a lot, if you will have more questions/issues please open new ticket
